---
# Redhat Release Name
redhat_linux_install_distro:

# Path to the build files in Repository server
redhat_linux_install_repo_dir:

# Tftp boot directory path in PXE server
redhat_linux_install_base_dir: /var/lib/tftpboot/

# Append base directory path with a new directory named by mac address
redhat_linux_install_dest_dir: "{{ base_dir }}{{ mac_address }}"

# Set core elf file path in PXE server
redhat_linux_install_core_file_path: "{{ mac_address }}/boot/grub/powerpc-ieee1275/core.elf"

# HMC credentials
redhat_linux_install_curr_hmc_auth:
        username: "{{ hostvars[groups['hmcs'][0]].ansible_user }}"
        password: "{{ hostvars[groups['hmcs'][0]].ansible_password }}"

# Host Details
redhat_linux_install_host_ip: 9.1.1.10
redhat_linux_install_host_gw: 9.1.1.1
redhat_linux_install_host_subnet: 9.1.1.0
redhat_linux_install_host_netmask: 255.255.255.0
redhat_linux_install_dns_ip: 9.0.0.0
redhat_linux_install_hostname: vm.abc.com
redhat_linux_install_lpar_name: vm-hmc
redhat_linux_install_managed_system: vm-abc
redhat_linux_install_host_password: abc123
redhat_linux_install_proc: 2
redhat_linux_install_disk_size: 28590
redhat_linux_install_mem: 2048
